<a href="https://colab.research.google.com/github/AvantiShri/colab_notebooks/blob/master/misc/PlayWithColetteData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas

In [121]:
df = pandas.read_csv("200413_nitrous_oxide_cycling_regimes_data_for_repositories.csv")

From Colette:

```
So this whole thing started with a plots of N2O isotopomers (columns "d15N-N2Oa_mean (per mil vs. atm N2)", "d15N-N2Ob_mean 
(per mil vs. atm. N2)", and "d18O-N2O_mean (per mil vs. VSMOW)") vs. the inverse of N2O concentration (1/"N2O_mean (nM)"). They are 
a figure in my paper. These plots had a visible change point in them. Patrick has noticed a similar phenomenon in his data. The two 
clusters on a plot like this indicate two different pools of N2O produced from two different sources.

I strongly suspect that nitrite concentration ("Nitrite [uM]" in the spreadsheet) and oxygen ("Seabird Oxygen [umol/L]") also inform the clustering. 
Also the isotopes of nitrite and nitrate ("d18O-NO3 avg (per mil vs. VSMOW)" and so forth). Furthermore I feel like the degree to which they inform 
clustering actually gives us additional information as well. For example, if nitrite concentration is a strong predictor whether a datapoint falls into one 
cluster or another, that tells me that nitrite is likely a substrate for one of these N2O pools.
```

In [152]:
from matplotlib import pyplot as plt

#Easy remapping of the column names
colnames_map = {'d15N_N2Oa_mean':"d15N-N2Oa_mean (per mil vs. atm N2)",
            'd15N_N2Ob_mean':"d15N-N2Ob_mean (per mil vs. atm. N2)",
            'd18O_N2O_mean':"d18O-N2O_mean (per mil vs. VSMOW)",
            'N2O_mean':"N2O_mean (nM)",
            'Nitrite':"Nitrite [uM]",
            'Oxygen':"Seabird Oxygen [umol/L]",
            'NO3_mean':'NO3_mean (uM)',
            'd18O_NO3_mean':'d18O-NO3 avg (per mil vs. VSMOW)',
            'd15N_NO3_mean':'d15N-NO3 avg (per mil vs. atm. N2)'}


#For some reason, altair chokes when provided data frames with some
# of the original column names. So I am remapping the column names.
def remap_colnames(df, colnames_map):
  #comment out the code that was for filtering out nan vals, as it
  # is not necessary; altair can handle nans
  #orig_cols = list(colnames_map.values())
  #nan_filter = df[orig_cols[0]].notnull()
  #for col in orig_cols[1:]:
  #  nan_filter &= df[col].notnull()
  #new_df_cols = df.copy() #df[nan_filter].copy()
  foraltair_df = pandas.DataFrame(dict([
      (new_col, np.array(df[orig_col]))
      for new_col,orig_col in colnames_map.items()]))
  return foraltair_df

#create a column for the inverse of the N2O mean
filtered_df = do_nanfilter(df=df, colnames_map=colnames_map)
filtered_df['inv_N2O_mean'] = 1/filtered_df['N2O_mean']

In [154]:
import altair as alt

interval = alt.selection_interval()

invN2O_base = alt.Chart(filtered_df).mark_point().encode(
  x='inv_N2O_mean',
  color=alt.condition(interval, 'Oxygen', alt.value('lightgray'))
).properties(
  selection=interval
)

#alt.vconcat(
(invN2O_base.encode(y='d15N_N2Oa_mean')
| invN2O_base.encode(y='d15N_N2Ob_mean')
| invN2O_base.encode(y='d18O_N2O_mean')
)

alt.HConcatChart(...)

In [133]:
base

alt.Chart(...)

In [105]:
filtered_df

Station  Cast  ...  copy_d15N_N2Ob_mean  copy_d18O_N2O_mean
0       PS1     2  ...                 -1.0                47.2
1       PS1     2  ...                 -1.1                53.1
2       PS1     2  ...                 -0.1                64.8
3       PS1     2  ...                 -0.3                58.9
4       PS1     2  ...                 -2.8                59.2
..      ...   ...  ...                  ...                 ...
213      T6    68  ...                 -7.1                80.4
214      T6    68  ...                 -4.9                60.9
215      T6    68  ...                 -3.1                55.7
216      T6    68  ...                 -2.6                55.5
217      T6    68  ...                 -4.2                56.1

[212 rows x 47 columns]

In [93]:
#np.isnan(filtered_df[colnames.d15N_N2Oa_mean])
alt.Chart(filtered_df).mark_point().encode(
  x='inv_N2O_mean',
  y='newcol'
  #y=colnames.d15N_N2Oa_mean,
)

alt.Chart(...)

In [87]:
filtered_df['newcol'] = np.array(filtered_df[colnames.d15N_N2Oa_mean]).copy()

In [90]:
filtered_df[colnames.d15N_N2Oa_mean] = np.array(filtered_df[colnames.d15N_N2Oa_mean]).copy()

In [96]:
filtered_df[colnames.d15N_N2Oa_mean]

0      12.5
1      15.9
2      22.6
3      19.1
4      18.8
       ... 
213    29.8
214    18.2
215    17.9
216    19.5
217    22.5
Name: d15N-N2Oa_mean (per mil vs. atm N2), Length: 212, dtype: float64

In [97]:
filtered_df['newcol']

0      12.5
1      15.9
2      22.6
3      19.1
4      18.8
       ... 
213    29.8
214    18.2
215    17.9
216    19.5
217    22.5
Name: newcol, Length: 212, dtype: float64

In [81]:
np.array(filtered_df.loc[:,colnames.d15N_N2Oa_mean])

array([12.5, 15.9, 22.6, 19.1, 18.8, 13.7, 18.8, 19.8, 20.2, 20.5, 21.6,
       18. , 17. , 15.3,  9.2, 11.4, 11.1, 10.8, 11. , 13.1, 11.3, 11.7,
       11.6, 13.9, 10.8, 10.6, 10.8, 39.2, 44. , 37.6, 39.2, 40.5, 15.4,
       37.9, 23. , 23.1, 28.8, 26.9, 21. , 19.3, 19.3, 20.3, 20.8, 21.6,
       21. , 15.7, 11.3,  9.4, 10.6, 10.6, 12.3, 28.4, 37.6,  5.3,  5.6,
        4.9,  4.6,  3.5,  6. ,  8.4, 10.9, 12.6, 18.6, 27.3, 32.7, 33.1,
       25. , 31.8, 32.2, 28.6, 37.1, 43. , 39.6, 22.6, 17.3, 41.5, 16.8,
       16.5, 16.4, 15.1,  9.6,  8.5,  7.7,  7.3,  8.5, 10.9, 12.8, 12.3,
       11.8, 18.9, 31.2, 41.8, 25.6, 28.1, 13.7, 19.6, 21. , 22. , 15.4,
       16.9, 16.1, 15.1, 15.3,  9.4,  9.3,  8.6,  9.2,  9.8, 15.9, 18.5,
       28.5, 28.4, 21.3, 26.4, 40.2, 43.6, 27. , 26.7, 20.3, 21.2, 22.6,
       17.2, 15.2, 14. , 14.6, 10.8,  8.4,  8.4,  7.9,  8.6,  9.1, 10.9,
       14.4, 24.1, 19.4, 28.2, 31.7,  8.5, 33.5, 23.8, 28.3, 18.8, 19.6,
       20.4, 16.4, 14.2,  8.8,  9.7, 10. , 11.8, 13

In [74]:
filtered_df['newcol']

0      12.5
1      15.9
2      22.6
3      19.1
4      18.8
       ... 
213    29.8
214    18.2
215    17.9
216    19.5
217    22.5
Name: newcol, Length: 212, dtype: float64

In [71]:
np.array(filtered_df[colnames.d15N_N2Oa_mean])

array([12.5, 15.9, 22.6, 19.1, 18.8, 13.7, 18.8, 19.8, 20.2, 20.5, 21.6,
       18. , 17. , 15.3,  9.2, 11.4, 11.1, 10.8, 11. , 13.1, 11.3, 11.7,
       11.6, 13.9, 10.8, 10.6, 10.8, 39.2, 44. , 37.6, 39.2, 40.5, 15.4,
       37.9, 23. , 23.1, 28.8, 26.9, 21. , 19.3, 19.3, 20.3, 20.8, 21.6,
       21. , 15.7, 11.3,  9.4, 10.6, 10.6, 12.3, 28.4, 37.6,  5.3,  5.6,
        4.9,  4.6,  3.5,  6. ,  8.4, 10.9, 12.6, 18.6, 27.3, 32.7, 33.1,
       25. , 31.8, 32.2, 28.6, 37.1, 43. , 39.6, 22.6, 17.3, 41.5, 16.8,
       16.5, 16.4, 15.1,  9.6,  8.5,  7.7,  7.3,  8.5, 10.9, 12.8, 12.3,
       11.8, 18.9, 31.2, 41.8, 25.6, 28.1, 13.7, 19.6, 21. , 22. , 15.4,
       16.9, 16.1, 15.1, 15.3,  9.4,  9.3,  8.6,  9.2,  9.8, 15.9, 18.5,
       28.5, 28.4, 21.3, 26.4, 40.2, 43.6, 27. , 26.7, 20.3, 21.2, 22.6,
       17.2, 15.2, 14. , 14.6, 10.8,  8.4,  8.4,  7.9,  8.6,  9.1, 10.9,
       14.4, 24.1, 19.4, 28.2, 31.7,  8.5, 33.5, 23.8, 28.3, 18.8, 19.6,
       20.4, 16.4, 14.2,  8.8,  9.7, 10. , 11.8, 13

In [67]:
filtered_df[:10]

Station  Cast  Target Depth [m]  ...  N2O_Flag_1  N2O_Flag_2  inv_N2O_mean
0     PS1     2               220  ...         NaN         NaN      0.011136
1     PS1     2               300  ...         NaN         NaN      0.014620
2     PS1     2               400  ...         NaN         NaN      0.015576
3     PS1     2               500  ...         NaN         NaN      0.015898
4     PS1     2               600  ...         NaN         NaN      0.014065
5     PS1     2               700  ...         NaN         NaN      0.015552
6     PS1     2               800  ...         NaN         NaN      0.013387
7     PS1     2               900  ...         NaN         NaN      0.015674
8     PS1     2              1000  ...         NaN         NaN      0.016447
9     PS1     2              1250  ...         NaN         4.0      0.029940

[10 rows x 44 columns]

In [64]:
import numpy as np
np.array(df['CTD_Pressure [db]'])

array([2.2540e+02, 3.0650e+02, 4.0650e+02, 5.0700e+02, 6.0800e+02,
       7.0960e+02, 8.0940e+02, 9.1130e+02, 1.0116e+03, 1.2650e+03,
       1.5162e+03, 1.0900e+01, 4.0500e+01, 5.0500e+01, 6.0300e+01,
       7.0600e+01, 8.1100e+01, 9.0700e+01, 1.0110e+02, 1.1120e+02,
       1.5140e+02, 1.8350e+02, 2.0370e+02, 3.2900e+01, 5.3500e+01,
       6.3200e+01, 7.3300e+01, 1.0370e+02, 1.5360e+02, 2.0500e+02,
       2.6490e+02, 3.0470e+02, 3.5500e+02, 4.0550e+02, 4.5580e+02,
       5.0620e+02, 5.5700e+02, 6.0700e+02, 8.0890e+02, 9.0950e+02,
       1.0101e+03, 1.2657e+03, 1.5192e+03, 2.0271e+03, 2.9422e+03,
       4.2000e+00, 5.5100e+01, 6.5100e+01, 7.5100e+01, 7.9900e+01,
       8.9600e+01, 1.3000e+02,        nan,        nan,        nan,
              nan, 3.0380e+02, 2.6000e+00, 1.1400e+01, 1.6600e+01,
       2.1200e+01, 2.6400e+01, 3.1400e+01,        nan, 4.1400e+01,
       4.6600e+01, 5.1700e+01, 6.2100e+01, 8.2000e+01, 9.2200e+01,
       1.0200e+02, 1.2220e+02, 1.4220e+02, 1.6220e+02, 2.0270e

In [60]:
filtered_df

Station  Cast  Target Depth [m]  ...  N2O_Flag_1  N2O_Flag_2  inv_N2O_mean
0       PS1     2               220  ...         NaN         NaN      0.011136
1       PS1     2               300  ...         NaN         NaN      0.014620
2       PS1     2               400  ...         NaN         NaN      0.015576
3       PS1     2               500  ...         NaN         NaN      0.015898
4       PS1     2               600  ...         NaN         NaN      0.014065
..      ...   ...               ...  ...         ...         ...           ...
213      T6    68               600  ...         NaN         NaN      0.030769
214      T6    68               800  ...         NaN         NaN      0.010905
215      T6    68              1000  ...         NaN         NaN      0.011669
216      T6    68              1250  ...         NaN         NaN      0.014793
217      T6    68              1500  ...         NaN         NaN      0.017094

[212 rows x 44 columns]